---
# Workflow to build NixOS from the flake
name: build-nixos
run-name: Build NixOS
on:
  push:
  pull_request:
jobs:
  build-os:
    strategy:
      matrix:
        host: [m625q, opx7070, sid, x13, x1c]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/cachix/install-nix-action
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      # https://nix.dev/tutorials/nixos/continuous-integration-github-actions
      - name: Cachix cache
        uses: cachix/cachix-action@v16
        with:
          name: timhourigan
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build
        # Using he equivalent of `nixos-rebuild build --flake .` as
        # the nix action does not have `nixos-rebuild``
        run: |
          nix-prefetch-url --name displaylink-600.zip https://www.synaptics.com/sites/default/files/exe_files/2024-05/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.0-EXE.zip
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
        timeout-minutes: 15
