# Workflow to test the flake
name: test-flake
run-name: Test flake
on:
  push:
    # branches:
    #   - main
  pull_request:
    branches:
      - main
jobs:
  run-make-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/cachix/install-nix-action
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - name: Run make help
        run: make help
