# Workflow to build the flake
name: build-flake
run-name: Build flake
on:
  push:
  pull_request:
jobs:
  run-make-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/cachix/install-nix-action
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - name: Build
      # Using he equivalent of `nixos-rebuild build --flake .#x13` as
      # the nix action does not have nixos-rebuild
        run: |
          nix-prefetch-url --name displaylink-580.zip https://www.synaptics.com/sites/default/files/exe_files/2023-08/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.8-EXE.zip
          nix build .#nixosConfigurations.x13.config.system.build.toplevel
