# Workflow to build the flake
name: build-flake
run-name: Build flake
on:
  push:
  pull_request:
jobs:
  run-make-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/cachix/install-nix-action
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - name: Run make build
        run: make build
        env:
          USER: timh
          HOSTNAME: x13
